version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "type: auto"
      - "type: deps"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - "type: auto"
      - "type: deps"
      - "type: actions"
