project_id: '500746'
api_token_env: CROWDIN_API_TOKEN
base_path: /
base_url: 'https://api.crowdin.com'
preserve_hierarchy: true
commit_message: 'feat(i18n): '
pull_request_title: 'feat(i18n): update translations'
pull_request_labels: [ 'i18n', 'auto' ]
files:
  - source: src/main/resources/assets/scpsharp/lang/zh_cn.json
    translation: /%original_path%/src/main/resources/assets/scpsharp/lang/%locale_with_underscore%.json
