preserve_hierarchy: false
commit_message: 'feat(i18n): '
pull_request_title: 'feat(i18n): update translations'
pull_request_labels: [ 'i18n', 'auto' ]
files:
  - source: src/main/resources/assets/scpsharp/lang/zh_cn.json
    translation: /%original_path%/%locale_with_underscore%.json
