name: Translation Correction
description: Ahha, no!
title: "[i18n] <title>"
labels:
  - "type: i18n"
body:
  - type: markdown
    attributes:
      value: |
        #### [Crowdin](https://crowdin.com/project/scp-sharp) is better than creating a issue!
  - type: input
    attributes:
      label: Version
      description: Included the mod version and the game version.
    validations:
      required: true
  - type: input
    attributes:
      label: Language
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
    validations:
      required: true
