name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: 18
          distribution: adopt
          cache: gradle

      - name: Cache .gradle
        uses: actions/cache@v4
        with:
          path: $USER_HOME/.gradle
          key: ${{ runner.os }}-${{ hashFiles('*.gradle') }}-gradle-user-home

      - name: Build
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: |
          chmod +x ./gradlew
          ./gradlew spotlessApply build
          git config --global user.email action@github.com
          git config --global user.name github-actions
          git commit -m "style(license): format license header [ci skip]" -a || true
          git push || true

      - name: Publish
        if: github.event_name == 'release'
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: ./gradlew publish modrinth

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/libs

      - name: Upload Release
        uses: fnkr/github-action-ghr@v1
        if: github.event_name == 'release'
        env:
          GHR_PATH: build/libs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
