name: Lock Inactive Issues

on:
  workflow_dispatch:
  schedule:
    - cron: "30 5 * * */3"

jobs:
  close-issues:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v5.1.1
        with:
          days-before-stale: 30
          days-before-close: 7
          stale-issue-label: "status: stale"
          stale-pr-label: "status: stale"
          exempt-issue-labels: "flag: long"
          exempt-pr-labels: "flag: long"
          exempt-draft-pr: true
